pages:
  - Home: index.md
  - Pronounce American:
    - Vowel Sounds: English/Pronounce/vowel.md
    - Consonant Sounds: English/Pronounce/consonant.md
    - Other Sounds: English/Pronounce/other.md
  - Word:
    - Noun:
      - Animal: English/Word/Noun/1_animal.md
      - Fruits and Vegetables: English/Word/Noun/2_fruits.md
      - Types of Food and Drinks: English/Word/Noun/3_food.md
      - Plant and Flower: English/Word/Noun/4_plant.md
      - Clothes Vocabulary: English/Word/Noun/5_clothes.md
      - Types of Shoes: English/Word/Noun/6_shoes.md
      - Colours and Shapes: English/Word/Noun/7_colours and Shapes.md
      - Mathematical: English/Word/Noun/8_Mathematical.md
      - Jobs: English/Word/Noun/9_job.md
    - Adj:
      - List of Adjectives: English/Word/Adj/1_adjectives.md
      - Family Members: English/Word/Adj/2_Family.md
      - Body Parts: English/Word/Adj/3_Body.md
      - Health and Healthcare: English/Word/Adj/4_Health.md
      - School: English/Word/Adj/5_School.md
      - Transportation and Vehicles: English/Word/Adj/6_Transportation.md
  - Effortless English:
    - Original English Audio: English/Effortless/Original/index.md
  - Crazy English:
    - 900 cau co ban (lession 1->20): English/Crazy/900_basic_1_20.md
    - 900 cau co ban (lession 20->40): English/Crazy/900_basic_20_40.md
    - 900 cau co ban (lession 40->60): English/Crazy/900_basic_40_60.md
    - 900 cau cuoc song (lession 1->20): English/Crazy/900_life_1_20.md
    - 900 cau cuoc song (lession 20->40): English/Crazy/900_life_20_40.md
    - 900 cau cuoc song (lession 40->60): English/Crazy/900_life_40_60.md

# Thông tin trang web
site_name: Learn English
repo_name: KNOWLEDGE BASED SYSTEMS
site_author: Toanph
copyright: '©2017: Toanph'
site_description: 'Contact: Email toanph1505@gmail.com;  Skype toanph1505'
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true


