pages:
  - Home: index.md
  - Pronounce American:
    - Vowel Sounds: English/Pronounce/vowel.md
    - Consonant Sounds: English/Pronounce/consonant.md
    - Other Sounds: English/Pronounce/other.md
  - Word (2740):
    - Noun:
      - Animal (125): English/Word/Noun/1_animal.md
      - Fruits and Vegetables (76): English/Word/Noun/2_fruits.md
      - Types of Food and Drinks (98): English/Word/Noun/3_food.md
      - Plant and Flower (58): English/Word/Noun/4_plant.md
      - Clothes Vocabulary (115): English/Word/Noun/5_clothes.md
      - Types of Shoes (68): English/Word/Noun/6_shoes.md
      - Colours and Shapes (48): English/Word/Noun/7_colours and Shapes.md
      - Mathematical (68): English/Word/Noun/8_Mathematical.md
      - Jobs (56): English/Word/Noun/9_job.md
    - Adj:
      - List of Adjectives (250): English/Word/Adj/1_adjectives.md
      - Family Members (44): English/Word/Adj/2_Family.md
      - Body Parts (112): English/Word/Adj/3_Body.md
      - Health and Healthcare (94): English/Word/Adj/4_Health.md
      - School (95): English/Word/Adj/5_School.md
      - Transportation and Vehicles (168): English/Word/Adj/6_Transportation.md
      - List of Holidays (172): English/Word/Adj/7_Holidays.md
      - House Vocabulary (83): English/Word/Adj/8_House.md
      - Types of Furniture (101): English/Word/Adj/9_Furniture.md
      - Kitchenware (89): English/Word/Adj/9_Kitchenware.md
      - Tools and Equipment (298): English/Word/Adj/10_Equipment.md
    - Hobbies:
      - Tools and Equipment (76): English/Word/Hobbies/1_Sports.md
      - Outdoor Games (81): English/Word/Hobbies/2_Outdoor.md
      - Common Verbs (228): English/Word/Hobbies/3_Verbs.md
      - Seasons and Natural (136): English/Word/Hobbies/4_Seasons.md
  - Effortless English:
    - Original English Audio: English/Effortless/Original/index.md
  - Crazy English:
    - 900 cau co ban (lession 1->20): English/Crazy/900_basic_1_20.md
    - 900 cau co ban (lession 20->40): English/Crazy/900_basic_20_40.md
    - 900 cau co ban (lession 40->60): English/Crazy/900_basic_40_60.md
    - 900 cau cuoc song (lession 1->20): English/Crazy/900_life_1_20.md
    - 900 cau cuoc song (lession 20->40): English/Crazy/900_life_20_40.md
    - 900 cau cuoc song (lession 40->60): English/Crazy/900_life_40_60.md

# Thông tin trang web
site_name: Learn English
repo_name: KNOWLEDGE BASED SYSTEMS
site_author: Toanph
copyright: '©2017: Toanph'
site_description: 'Contact: Email toanph1505@gmail.com;  Skype toanph1505'
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true


